[book]
authors = ["Patrick Sullivan"]
language = "en"
multilingual = false
src = "src"
title = "Acidic Book"
description = "A book on all things Acidic"

[build]
create-missing = false

[preprocessor.external-links]

[output.html]
git-repository-url = "https://github.com/storm-software/acidic-book"
edit-url-template = "https://github.com/storm-software/acidic-book/edit/master/{path}"
default-theme = "ayu"
additional-js = ["src/static/solidity.min.js"]
cname = "book.acidic.io"
additional-css = ["src/static/custom.css"]

[output.html.fold]
enable = true
level = 1