[toolchain]
channel = "1.98.0"
components = [
    "rustc",
    "cargo",
    "clippy",
    "rustfmt",
    "rust-analyzer",
    "rust-docs",
    "rust-std",
]
profile = "default"
targets = ["x86_64-unknown-linux-gnu", "wasm32-wasip1-threads"]

# components = ["llvm-tools"]
