/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Context {
  schema: JsSchema
  kind: number
}
export interface Schema {
  identifier?: string
  models: Record<string, Model>
  definitions: Record<string, Definition>
  dataSources: Record<string, DataSource>
  plugins: Record<string, Plugin>
  enumerations: Record<string, Enumeration>
  attributes: Array<Attribute>
  comments: Array<string>
}
/** An argument, either for attributes or for function call expressions. */
export interface Argument {
  /**
   * The argument identifier, if applicable.
   *
   * ```ignore
   * @id(map: "myIndex")
   *     ^^^
   * ```
   */
  identifier?: string
  /**
   * The argument value.
   *
   * ```ignore
   * @id("myIndex")
   *     ^^^^^^^^^
   * ```
   */
  value: Expression
  /**
   * The argument default value.
   *
   * ```ignore
   * @id(map: String = "myIndex")
   *                   ^^^^^^^^^
   * ```
   */
  default?: Expression
}
/**
 * An attribute (following `@` or `@@``) on a model, model field, enum, enum value or composite
 * type field.
 */
export interface Attribute {
  /**
   * The name of the attribute:
   *
   * ```ignore
   * @@index([a, b, c])
   *   ^^^^^
   * ```
   */
  identifier: string
  /**
   * The arguments of the attribute.
   *
   * ```ignore
   * @@index([a, b, c], map: "myidix")
   *         ^^^^^^^^^^^^^^^^^^^^^^^^
   * ```
   */
  arguments: Argument
}
/**
 * A named property in a config block.
 *
 * ```ignore
 * datasource db {
 *     url = env("URL")
 *     ^^^^^^^^^^^^^^^^
 * }
 * ```
 */
export interface ConfigProperty {
  /**
   * The property name.
   *
   * ```ignore
   * datasource db {
   *     url = env("URL")
   *     ^^^
   * }
   * ```
   *
   */
  identifier: string
  /**
   * The property value.
   *
   * ```ignore
   * datasource db {
   *     url = env("URL")
   *           ^^^^^^^^^^
   * }
   * ```
   */
  value?: Expression
}
/** a `datasource` from the schema. */
export interface DataSource {
  identifier: string
  /** The provider string */
  provider: string
  url: string
  directUrl?: string
  /** An optional user-defined shadow database URL. */
  shadowDatabaseUrl?: string
  comments: Array<string>
  attributes: Array<Attribute>
  /** _Sorted_ vec of schemas defined in the schemas property. */
  namespaces: Array<string>
  properties: Record<string, ConfigProperty>
}
/** A Definition declaration. */
export interface Definition {
  /**
   * The name of the Definition.
   *
   * ```ignore
   * type Foo { .. }
   *       ^^^
   * ```
   */
  identifier: string
  /**
   * The fields of the Definition.
   *
   * ```ignore
   * type Foo {
   *   id    Int    @id
   *   ^^^^^^^^^^^^^^^^
   *   field String
   *   ^^^^^^^^^^^^
   * }
   * ```
   */
  fields: Record<string, Field>
  /**
   * The attributes of this model.
   *
   * ```ignore
   * type Foo {
   * id    Int    @id
   * field String
   *
   * @@index([field])
   * ^^^^^^^^^^^^^^^^
   * @@map("Bar")
   * ^^^^^^^^^^^^
   * }
   * ```
   */
  attributes: Array<Attribute>
  /**
   * The documentation for this model.
   *
   * ```ignore
   * /// Lorem ipsum
   *     ^^^^^^^^^^^
   * model Foo {
   *   id    Int    @id
   *   field String
   * }
   * ```
   */
  comments: Array<string>
}
/**
 * An enum declaration. Enumeration can either be in the database schema, or completely a Prisma level concept.
 *
 * PostgreSQL stores enums in a schema, while in MySQL the information is in
 * the table definition. On MongoDB the enumerations are handled in the Query
 * Engine.
 */
export interface Enumeration {
  /**
   * The identifier of the enum.
   *
   * ```ignore
   * enum Foo { ... }
   *      ^^^
   * ```
   */
  identifier: string
  /**
   * The values of the enum.
   *
   * ```ignore
   * enum Foo {
   *   Value1
   *   ^^^^^^
   *   Value2
   *   ^^^^^^
   * }
   * ```
   */
  values: Record<string, EnumerationValue>
  /**
   * The attributes of this enum.
   *
   * ```ignore
   * enum Foo {
   *   Value1
   *   Value2
   *
   *   @@map("1Foo")
   *   ^^^^^^^^^^^^^
   * }
   * ```
   */
  attributes: Array<Attribute>
  /**
   * The comments for this enum.
   *
   * ```ignore
   * /// Lorem ipsum
   *     ^^^^^^^^^^^
   * enum Foo {
   *   Value1
   *   Value2
   * }
   * ```
   */
  comments: Array<string>
}
/** An enum value definition. */
export interface EnumerationValue {
  /** The name of the enum value as it will be exposed by the api. */
  identifier: string
  attributes: Array<Attribute>
  comments: Array<string>
}
export const enum ExpressionType {
  /** Any numeric value e.g. floats or ints. */
  NumericExpression = 'NumericExpression',
  /** Any string value. */
  StringExpression = 'StringExpression',
  /** Any boolean value (`true` or `false`). */
  BooleanExpression = 'BooleanExpression',
  /**
   * Any literal string that serves as a reference, basically a string which was not inside "...".
   * This is used for representing built-in enums or definition references.
   */
  ReferenceExpression = 'ReferenceExpression',
  /** A function call like node with a name and arguments. */
  FunctionExpression = 'FunctionExpression',
  /** An array of other values. */
  ArrayExpression = 'ArrayExpression'
}
export interface FunctionExpression {
  function: string
  arguments: Array<Argument>
}
export interface ReferenceExpression {
  value: ReferenceId
  parent?: ReferenceId
}
export interface Expression {
  expressionType: ExpressionType
  literal: string
  function?: FunctionExpression
  reference?: ReferenceExpression
  items?: Array<Expression>
}
/** A field definition in a model or a composite type. */
export interface Field {
  parentIdentifier: string
  /**
   * The name of the field.
   *
   * ```ignore
   * name String
   * ^^^^
   * ```
   */
  identifier: string
  /**
   * The field's type.
   *
   * ```ignore
   * name String
   *      ^^^^^^
   * ```
   */
  FieldType: JsFieldType
  /**
   * A flag indicating if the field is optional or required.
   *
   * ```ignore
   * name String?
   *            ^
   * ```
   */
  isOptional: boolean
  /**
   * A flag indicating if the field is an array.
   *
   * ```ignore
   * name String[]
   *            ^
   * ```
   */
  isArray: boolean
  /**
   * The attributes of this field.
   *
   * ```ignore
   * name String @id @default("my name")
   *             ^^^^^^^^^^^^^^^^^^^
   * ```
   */
  attributes: Array<Attribute>
  /**
   * The comments for this field.
   *
   * ```ignore
   * /// Lorem ipsum
   *     ^^^^^^^^^^^
   * name String @id @default("my name")
   * ```
   */
  comments: Array<string>
}
/** An arity of a data model field. */
export const enum FieldType {
  String = 'String',
  Boolean = 'Boolean',
  Float = 'Float',
  Decimal = 'Decimal',
  Integer = 'Integer',
  BigInt = 'BigInt',
  DateTime = 'DateTime',
  Date = 'Date',
  Time = 'Time',
  Json = 'Json',
  Reference = 'Reference',
  Bytes = 'Bytes',
  Null = 'Null',
  Any = 'Any'
}
/** A model declaration. */
export interface Model {
  /**
   * The name of the model.
   *
   * ```ignore
   * model Foo { .. }
   *       ^^^
   * ```
   */
  identifier: string
  /**
   * The fields of the model.
   *
   * ```ignore
   * model Foo {
   *   id    Int    @id
   *   ^^^^^^^^^^^^^^^^
   *   field String
   *   ^^^^^^^^^^^^
   * }
   * ```
   */
  fields: Record<string, Field>
  /**
   * The attributes of this model.
   *
   * ```ignore
   * type Foo {
   * id    Int    @id
   * field String
   *
   * @@index([field])
   * ^^^^^^^^^^^^^^^^
   * @@map("Bar")
   * ^^^^^^^^^^^^
   * }
   * ```
   */
  attributes: Array<Attribute>
  /**
   * The documentation for this model.
   *
   * ```ignore
   * /// Lorem ipsum
   *     ^^^^^^^^^^^
   * model Foo {
   *   id    Int    @id
   *   field String
   * }
   * ```
   */
  comments: Array<string>
  /**
   * Is the model defined as a view in the database.
   *
   * ```ignore
   * view Foo {
   *   val Int @unique
   * }
   * ```
   */
  isView: boolean
}
export const enum NodeKind {
  Model = 'Model',
  Definition = 'Definition',
  Enumeration = 'Enumeration',
  EnumerationValue = 'EnumerationValue',
  Field = 'Field',
  Event = 'Event',
  Query = 'Query',
  Mutation = 'Mutation',
  Subscription = 'Subscription',
  Plugin = 'Plugin',
  DateSource = 'DateSource',
  Schema = 'Schema'
}
/** a `datasource` from the schema. */
export interface Plugin {
  identifier: string
  /** The provider string */
  provider: string
  output?: string
  comments: Array<string>
  attributes: Array<Attribute>
  properties: Record<string, ConfigProperty>
}
/** An Acidic schema node ReferenceId. */
export interface ReferenceId {
  /** The node contents. */
  identifier: string
  /** The kind of the schema node. */
  kind: NodeKind
}
export class JsTemplateAdapter {
  getEngine(): JsTemplateEngine
}
export type JsTemplateEngine = TemplateEngine
export class TemplateEngine { }
