[package]
name = "acidic-rpc"
description = "A core crate containing the Acidic schema definitions and validation logic."
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
homepage = { workspace = true }
documentation = "https://docs.rs/acidic-rpc"
readme = "./README.md"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }

[build-dependencies]
prost = { workspace = true }
protoc-bin-vendored = { workspace = true }
storm-workspace = { workspace = true }
itertools = { workspace = true }
tempfile = { workspace = true }
tonic-build = { workspace = true, default-features = false, features = [
    "prost",
    "cleanup-markdown",
] }
