---
name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

env:
  CI: true
  NX_DAEMON: false
  NX_VERBOSE_LOGGING: true
  SKIP_ENV_VALIDATION: true
  GITHUB_ACTOR: stormie-bot
  GITHUB_TOKEN: ${{ secrets.STORMIE_GITHUB_TOKEN }}

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.STORMIE_GITHUB_TOKEN }}

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.STORMIE_GITHUB_TOKEN }}
